# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
builds:
  - id: 'slurm-23.11'
    main: ./cmd/prometheus-slurm-exporter/main.go
    binary: prometheus-slurm-exporter_slurm-23.11_{{ .Os }}_{{ .Arch }}
    flags:
      - -tags=2311
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: 'slurm-24.05'
    main: ./cmd/prometheus-slurm-exporter/main.go
    binary: prometheus-slurm-exporter_slurm-24.05_{{ .Os }}_{{ .Arch }}
    flags:
      - -tags=2405
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: 'slurm-24.11'
    main: ./cmd/prometheus-slurm-exporter/main.go
    binary: prometheus-slurm-exporter_slurm-24.11_{{ .Os }}_{{ .Arch }}
    flags:
      - -tags=2411
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
